### ISSUE TITLE
Request for Release of Training Code

### ISSUE THREAD

**Issue by shnhrtkyk** [sixu0/SeisCLIP#2]
Hi,

I am writing to inquire if there are any plans to release the training code for your good project. The availability of the training code would greatly benefit the community and facilitate further research and development.

Thank you for your time and consideration.

**Comment by sixu0** [comment]
Thanks for your attention. I've updated the pre-training code, and the training code for downstream tasks will be released later.
BTW: Which specific downstream task are you interested in? I can prioritize its release accordingly.

**Comment by shnhrtkyk** [comment]
thank you
